#!/bin/bash

if ! hash mono 2> /dev/null
then
	echo "'mono' was not found in PATH."
	echo "This application requires mono to be installed."
	exit 1
fi

# Get the directory this script is in, so we can change to it so mono can find all the files.
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"

cd $DIR/lib

mono LegacyOfTheAncients.exe

