#define Win32
using System.Diagnostics;
using System.Data;
using System;
using System.Windows.Forms;
using AxComCtl3;
using AxMSComCtl2;
using ERY.Xle;
using ERY.AgateLib;
using System.Drawing;
using Microsoft.VisualBasic;
using System.Collections;
using Microsoft.VisualBasic.Compatibility;
using System.Linq;
using System.IO;
using ERY.AgateLib.WinForms;

namespace XleMapEditor
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated()]public partial class frmImport
	{
		#region "Windows Form Designer generated code "
		[System.Diagnostics.DebuggerNonUserCode()]public frmImport()
		{
			//This call is required by the Windows Form Designer.
			InitializeComponent();
		}
		//Form overrides dispose to clean up the component list.
		[System.Diagnostics.DebuggerNonUserCode()]protected override void Dispose(bool Disposing)
		{
			if (Disposing)
			{
				if (components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose(Disposing);
		}
		//Required by the Windows Form Designer
		private System.ComponentModel.Container components = null;
		public System.Windows.Forms.ToolTip ToolTip1;
		public System.Windows.Forms.TextBox txtAreaHeight;
		public System.Windows.Forms.TextBox txtAreaWidth;
		public System.Windows.Forms.Button Command1;
		public System.Windows.Forms.Button cmdCancel;
		public System.Windows.Forms.Button cmdOK;
		public System.Windows.Forms.RadioButton _optTiles_3;
		public System.Windows.Forms.RadioButton _optTiles_4;
		public System.Windows.Forms.RadioButton _optTiles_0;
		public System.Windows.Forms.RadioButton _optTiles_1;
		public System.Windows.Forms.RadioButton _optTiles_2;
		public System.Windows.Forms.GroupBox Frame2;
		public System.Windows.Forms.CheckBox chkAuto;
		public System.Windows.Forms.RadioButton _optType_1;
		public System.Windows.Forms.RadioButton _optType_2;
		public System.Windows.Forms.RadioButton _optType_3;
		public System.Windows.Forms.RadioButton _optType_5;
		public System.Windows.Forms.RadioButton _optType_4;
		public System.Windows.Forms.RadioButton _optType_6;
		public System.Windows.Forms.TextBox txtFileOffset;
		public System.Windows.Forms.TextBox txtHeight;
		public System.Windows.Forms.TextBox txtWidth;
		public System.Windows.Forms.TextBox txtBpT;
		public System.Windows.Forms.Label upd;
		public System.Windows.Forms.Label Label2;
		public System.Windows.Forms.Label Label3;
		public System.Windows.Forms.Label Label8;
		public System.Windows.Forms.Label Label9;
		public System.Windows.Forms.GroupBox Frame1;
		public System.Windows.Forms.Label Label5;
		public System.Windows.Forms.Label Label4;
		public System.Windows.Forms.Label Label1;
		public Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray optTiles;
		public Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray optType;
		//NOTE: The following procedure is required by the Windows Form Designer
		//It can be modified using the Windows Form Designer.
		//Do not modify it using the code editor.
		[System.Diagnostics.DebuggerStepThrough()]private void InitializeComponent()
		{
			System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(frmImport));
			this.components = new System.ComponentModel.Container();
			this.ToolTip1 = new System.Windows.Forms.ToolTip(components);
			this.txtAreaHeight = new System.Windows.Forms.TextBox();
			this.txtAreaHeight.TextChanged += new System.EventHandler(txtAreaHeight_TextChanged);
			this.txtAreaWidth = new System.Windows.Forms.TextBox();
			this.txtAreaWidth.TextChanged += new System.EventHandler(txtAreaWidth_TextChanged);
			this.Command1 = new System.Windows.Forms.Button();
			this.cmdCancel = new System.Windows.Forms.Button();
			this.cmdCancel.Click += new System.EventHandler(cmdCancel_Click);
			this.cmdOK = new System.Windows.Forms.Button();
			this.cmdOK.Click += new System.EventHandler(cmdOK_Click);
			this.Frame2 = new System.Windows.Forms.GroupBox();
			this._optTiles_3 = new System.Windows.Forms.RadioButton();
			this._optTiles_4 = new System.Windows.Forms.RadioButton();
			this._optTiles_0 = new System.Windows.Forms.RadioButton();
			this._optTiles_1 = new System.Windows.Forms.RadioButton();
			this._optTiles_2 = new System.Windows.Forms.RadioButton();
			this.Frame1 = new System.Windows.Forms.GroupBox();
			this.chkAuto = new System.Windows.Forms.CheckBox();
			this.chkAuto.CheckStateChanged += new System.EventHandler(chkAuto_CheckStateChanged);
			this._optType_1 = new System.Windows.Forms.RadioButton();
			this._optType_2 = new System.Windows.Forms.RadioButton();
			this._optType_3 = new System.Windows.Forms.RadioButton();
			this._optType_5 = new System.Windows.Forms.RadioButton();
			this._optType_4 = new System.Windows.Forms.RadioButton();
			this._optType_6 = new System.Windows.Forms.RadioButton();
			this.txtFileOffset = new System.Windows.Forms.TextBox();
			this.txtFileOffset.TextChanged += new System.EventHandler(txtFileOffset_TextChanged);
			this.txtHeight = new System.Windows.Forms.TextBox();
			this.txtHeight.TextChanged += new System.EventHandler(txtHeight_TextChanged);
			this.txtWidth = new System.Windows.Forms.TextBox();
			this.txtWidth.TextChanged += new System.EventHandler(txtWidth_TextChanged);
			this.txtBpT = new System.Windows.Forms.TextBox();
			this.upd = new System.Windows.Forms.Label();
			this.Label2 = new System.Windows.Forms.Label();
			this.Label3 = new System.Windows.Forms.Label();
			this.Label8 = new System.Windows.Forms.Label();
			this.Label9 = new System.Windows.Forms.Label();
			this.Label5 = new System.Windows.Forms.Label();
			this.Label4 = new System.Windows.Forms.Label();
			this.Label1 = new System.Windows.Forms.Label();
			this.optTiles = new Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray(components);
			this.optTiles.CheckedChanged += new System.EventHandler(optTiles_CheckedChanged);
			this.optType = new Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray(components);
			this.optType.CheckedChanged += new System.EventHandler(optType_CheckedChanged);
			this.Frame2.SuspendLayout();
			this.Frame1.SuspendLayout();
			this.SuspendLayout();
			this.ToolTip1.Active = true;
			((System.ComponentModel.ISupportInitialize) this.optTiles).BeginInit();
			((System.ComponentModel.ISupportInitialize) this.optType).BeginInit();
			this.Text = "Import Parameters";
			this.ClientSize = new System.Drawing.Size(420, 408);
			this.Location = new System.Drawing.Point(4, 30);
			this.StartPosition = System.Windows.Forms.FormStartPosition.WindowsDefaultLocation;
			this.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.SystemColors.Control;
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
			this.ControlBox = true;
			this.Enabled = true;
			this.KeyPreview = false;
			this.MaximizeBox = true;
			this.MinimizeBox = true;
			this.Cursor = System.Windows.Forms.Cursors.Default;
			this.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.ShowInTaskbar = true;
			this.HelpButton = false;
			this.WindowState = System.Windows.Forms.FormWindowState.Normal;
			this.Name = "frmImport";
			this.txtAreaHeight.AutoSize = false;
			this.txtAreaHeight.Size = new System.Drawing.Size(49, 19);
			this.txtAreaHeight.Location = new System.Drawing.Point(64, 320);
			this.txtAreaHeight.TabIndex = 30;
			this.txtAreaHeight.Text = "Text1";
			this.txtAreaHeight.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtAreaHeight.AcceptsReturn = true;
			this.txtAreaHeight.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtAreaHeight.BackColor = System.Drawing.SystemColors.Window;
			this.txtAreaHeight.CausesValidation = true;
			this.txtAreaHeight.Enabled = true;
			this.txtAreaHeight.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtAreaHeight.HideSelection = true;
			this.txtAreaHeight.ReadOnly = false;
			this.txtAreaHeight.MaxLength = 0;
			this.txtAreaHeight.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtAreaHeight.Multiline = false;
			this.txtAreaHeight.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtAreaHeight.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtAreaHeight.TabStop = true;
			this.txtAreaHeight.Visible = true;
			this.txtAreaHeight.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtAreaHeight.Name = "txtAreaHeight";
			this.txtAreaWidth.AutoSize = false;
			this.txtAreaWidth.Size = new System.Drawing.Size(49, 19);
			this.txtAreaWidth.Location = new System.Drawing.Point(64, 296);
			this.txtAreaWidth.TabIndex = 26;
			this.txtAreaWidth.Text = "Text1";
			this.txtAreaWidth.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtAreaWidth.AcceptsReturn = true;
			this.txtAreaWidth.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtAreaWidth.BackColor = System.Drawing.SystemColors.Window;
			this.txtAreaWidth.CausesValidation = true;
			this.txtAreaWidth.Enabled = true;
			this.txtAreaWidth.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtAreaWidth.HideSelection = true;
			this.txtAreaWidth.ReadOnly = false;
			this.txtAreaWidth.MaxLength = 0;
			this.txtAreaWidth.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtAreaWidth.Multiline = false;
			this.txtAreaWidth.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtAreaWidth.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtAreaWidth.TabStop = true;
			this.txtAreaWidth.Visible = true;
			this.txtAreaWidth.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtAreaWidth.Name = "txtAreaWidth";
			this.Command1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.Command1.Text = "Reset Mappings...";
			this.Command1.Size = new System.Drawing.Size(81, 41);
			this.Command1.Location = new System.Drawing.Point(8, 352);
			this.Command1.TabIndex = 25;
			this.Command1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Command1.BackColor = System.Drawing.SystemColors.Control;
			this.Command1.CausesValidation = true;
			this.Command1.Enabled = true;
			this.Command1.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Command1.Cursor = System.Windows.Forms.Cursors.Default;
			this.Command1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Command1.TabStop = true;
			this.Command1.Name = "Command1";
			this.cmdCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmdCancel.Text = "Cancel";
			this.cmdCancel.Size = new System.Drawing.Size(65, 25);
			this.cmdCancel.Location = new System.Drawing.Point(272, 368);
			this.cmdCancel.TabIndex = 24;
			this.cmdCancel.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.cmdCancel.BackColor = System.Drawing.SystemColors.Control;
			this.cmdCancel.CausesValidation = true;
			this.cmdCancel.Enabled = true;
			this.cmdCancel.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdCancel.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdCancel.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdCancel.TabStop = true;
			this.cmdCancel.Name = "cmdCancel";
			this.cmdOK.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmdOK.Text = "OK";
			this.AcceptButton = this.cmdOK;
			this.cmdOK.Size = new System.Drawing.Size(65, 25);
			this.cmdOK.Location = new System.Drawing.Point(344, 368);
			this.cmdOK.TabIndex = 23;
			this.cmdOK.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.cmdOK.BackColor = System.Drawing.SystemColors.Control;
			this.cmdOK.CausesValidation = true;
			this.cmdOK.Enabled = true;
			this.cmdOK.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdOK.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdOK.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdOK.TabStop = true;
			this.cmdOK.Name = "cmdOK";
			this.Frame2.Text = "Tile Set";
			this.Frame2.Size = new System.Drawing.Size(401, 89);
			this.Frame2.Location = new System.Drawing.Point(8, 176);
			this.Frame2.TabIndex = 17;
			this.Frame2.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Frame2.BackColor = System.Drawing.SystemColors.Control;
			this.Frame2.Enabled = true;
			this.Frame2.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Frame2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Frame2.Visible = true;
			this.Frame2.Name = "Frame2";
			this._optTiles_3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_3.Text = "LOB Tiles.bmp";
			this._optTiles_3.Enabled = false;
			this._optTiles_3.Size = new System.Drawing.Size(201, 17);
			this._optTiles_3.Location = new System.Drawing.Point(192, 16);
			this._optTiles_3.TabIndex = 22;
			this._optTiles_3.Tag = "LOB Tiles.bmp";
			this._optTiles_3.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optTiles_3.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_3.BackColor = System.Drawing.SystemColors.Control;
			this._optTiles_3.CausesValidation = true;
			this._optTiles_3.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optTiles_3.Cursor = System.Windows.Forms.Cursors.Default;
			this._optTiles_3.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optTiles_3.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optTiles_3.TabStop = true;
			this._optTiles_3.Checked = false;
			this._optTiles_3.Visible = true;
			this._optTiles_3.Name = "_optTiles_3";
			this._optTiles_4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_4.Text = "LOB TownTiles.bmp";
			this._optTiles_4.Enabled = false;
			this._optTiles_4.Size = new System.Drawing.Size(201, 17);
			this._optTiles_4.Location = new System.Drawing.Point(192, 40);
			this._optTiles_4.TabIndex = 21;
			this._optTiles_4.Tag = "LOB TownTiles.bmp";
			this._optTiles_4.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optTiles_4.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_4.BackColor = System.Drawing.SystemColors.Control;
			this._optTiles_4.CausesValidation = true;
			this._optTiles_4.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optTiles_4.Cursor = System.Windows.Forms.Cursors.Default;
			this._optTiles_4.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optTiles_4.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optTiles_4.TabStop = true;
			this._optTiles_4.Checked = false;
			this._optTiles_4.Visible = true;
			this._optTiles_4.Name = "_optTiles_4";
			this._optTiles_0.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_0.Text = "Tiles.bmp";
			this._optTiles_0.Size = new System.Drawing.Size(113, 17);
			this._optTiles_0.Location = new System.Drawing.Point(16, 16);
			this._optTiles_0.TabIndex = 20;
			this._optTiles_0.Tag = "Tiles.bmp";
			this._optTiles_0.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optTiles_0.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_0.BackColor = System.Drawing.SystemColors.Control;
			this._optTiles_0.CausesValidation = true;
			this._optTiles_0.Enabled = true;
			this._optTiles_0.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optTiles_0.Cursor = System.Windows.Forms.Cursors.Default;
			this._optTiles_0.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optTiles_0.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optTiles_0.TabStop = true;
			this._optTiles_0.Checked = false;
			this._optTiles_0.Visible = true;
			this._optTiles_0.Name = "_optTiles_0";
			this._optTiles_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_1.Text = "TownTiles.bmp";
			this._optTiles_1.Size = new System.Drawing.Size(161, 17);
			this._optTiles_1.Location = new System.Drawing.Point(16, 40);
			this._optTiles_1.TabIndex = 19;
			this._optTiles_1.Tag = "TownTiles.bmp";
			this._optTiles_1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optTiles_1.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_1.BackColor = System.Drawing.SystemColors.Control;
			this._optTiles_1.CausesValidation = true;
			this._optTiles_1.Enabled = true;
			this._optTiles_1.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optTiles_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._optTiles_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optTiles_1.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optTiles_1.TabStop = true;
			this._optTiles_1.Checked = false;
			this._optTiles_1.Visible = true;
			this._optTiles_1.Name = "_optTiles_1";
			this._optTiles_2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_2.Text = "CastleTiles.bmp";
			this._optTiles_2.Size = new System.Drawing.Size(161, 17);
			this._optTiles_2.Location = new System.Drawing.Point(16, 64);
			this._optTiles_2.TabIndex = 18;
			this._optTiles_2.Tag = "CastleTiles.bmp";
			this._optTiles_2.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optTiles_2.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTiles_2.BackColor = System.Drawing.SystemColors.Control;
			this._optTiles_2.CausesValidation = true;
			this._optTiles_2.Enabled = true;
			this._optTiles_2.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optTiles_2.Cursor = System.Windows.Forms.Cursors.Default;
			this._optTiles_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optTiles_2.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optTiles_2.TabStop = true;
			this._optTiles_2.Checked = false;
			this._optTiles_2.Visible = true;
			this._optTiles_2.Name = "_optTiles_2";
			this.Frame1.Text = "Map Type";
			this.Frame1.Size = new System.Drawing.Size(401, 153);
			this.Frame1.Location = new System.Drawing.Point(8, 16);
			this.Frame1.TabIndex = 0;
			this.Frame1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Frame1.BackColor = System.Drawing.SystemColors.Control;
			this.Frame1.Enabled = true;
			this.Frame1.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Frame1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Frame1.Visible = true;
			this.Frame1.Name = "Frame1";
			this.chkAuto.Text = "Auto";
			this.chkAuto.Size = new System.Drawing.Size(57, 17);
			this.chkAuto.Location = new System.Drawing.Point(328, 72);
			this.chkAuto.TabIndex = 16;
			this.chkAuto.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.chkAuto.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.chkAuto.FlatStyle = System.Windows.Forms.FlatStyle.Standard;
			this.chkAuto.BackColor = System.Drawing.SystemColors.Control;
			this.chkAuto.CausesValidation = true;
			this.chkAuto.Enabled = true;
			this.chkAuto.ForeColor = System.Drawing.SystemColors.ControlText;
			this.chkAuto.Cursor = System.Windows.Forms.Cursors.Default;
			this.chkAuto.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.chkAuto.Appearance = System.Windows.Forms.Appearance.Normal;
			this.chkAuto.TabStop = true;
			this.chkAuto.CheckState = System.Windows.Forms.CheckState.Unchecked;
			this.chkAuto.Visible = true;
			this.chkAuto.Name = "chkAuto";
			this._optType_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_1.Text = "Museum";
			this._optType_1.Enabled = false;
			this._optType_1.Size = new System.Drawing.Size(84, 17);
			this._optType_1.Location = new System.Drawing.Point(16, 24);
			this._optType_1.TabIndex = 11;
			this._optType_1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_1.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_1.BackColor = System.Drawing.SystemColors.Control;
			this._optType_1.CausesValidation = true;
			this._optType_1.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_1.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_1.TabStop = true;
			this._optType_1.Checked = false;
			this._optType_1.Visible = true;
			this._optType_1.Name = "_optType_1";
			this._optType_2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_2.Text = "Outside";
			this._optType_2.Size = new System.Drawing.Size(84, 17);
			this._optType_2.Location = new System.Drawing.Point(16, 44);
			this._optType_2.TabIndex = 10;
			this._optType_2.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_2.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_2.BackColor = System.Drawing.SystemColors.Control;
			this._optType_2.CausesValidation = true;
			this._optType_2.Enabled = true;
			this._optType_2.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_2.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_2.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_2.TabStop = true;
			this._optType_2.Checked = false;
			this._optType_2.Visible = true;
			this._optType_2.Name = "_optType_2";
			this._optType_3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_3.Text = "Town";
			this._optType_3.Size = new System.Drawing.Size(84, 17);
			this._optType_3.Location = new System.Drawing.Point(16, 63);
			this._optType_3.TabIndex = 9;
			this._optType_3.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_3.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_3.BackColor = System.Drawing.SystemColors.Control;
			this._optType_3.CausesValidation = true;
			this._optType_3.Enabled = true;
			this._optType_3.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_3.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_3.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_3.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_3.TabStop = true;
			this._optType_3.Checked = false;
			this._optType_3.Visible = true;
			this._optType_3.Name = "_optType_3";
			this._optType_5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_5.Text = "Castle";
			this._optType_5.Size = new System.Drawing.Size(84, 17);
			this._optType_5.Location = new System.Drawing.Point(16, 101);
			this._optType_5.TabIndex = 8;
			this._optType_5.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_5.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_5.BackColor = System.Drawing.SystemColors.Control;
			this._optType_5.CausesValidation = true;
			this._optType_5.Enabled = true;
			this._optType_5.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_5.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_5.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_5.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_5.TabStop = true;
			this._optType_5.Checked = false;
			this._optType_5.Visible = true;
			this._optType_5.Name = "_optType_5";
			this._optType_4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_4.Text = "Dungeon";
			this._optType_4.Enabled = false;
			this._optType_4.Size = new System.Drawing.Size(84, 17);
			this._optType_4.Location = new System.Drawing.Point(16, 82);
			this._optType_4.TabIndex = 7;
			this._optType_4.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_4.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_4.BackColor = System.Drawing.SystemColors.Control;
			this._optType_4.CausesValidation = true;
			this._optType_4.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_4.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_4.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_4.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_4.TabStop = true;
			this._optType_4.Checked = false;
			this._optType_4.Visible = true;
			this._optType_4.Name = "_optType_4";
			this._optType_6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_6.Text = "Temple";
			this._optType_6.Size = new System.Drawing.Size(84, 17);
			this._optType_6.Location = new System.Drawing.Point(16, 120);
			this._optType_6.TabIndex = 6;
			this._optType_6.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_6.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_6.BackColor = System.Drawing.SystemColors.Control;
			this._optType_6.CausesValidation = true;
			this._optType_6.Enabled = true;
			this._optType_6.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_6.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_6.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_6.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_6.TabStop = true;
			this._optType_6.Checked = false;
			this._optType_6.Visible = true;
			this._optType_6.Name = "_optType_6";
			this.txtFileOffset.AutoSize = false;
			this.txtFileOffset.Size = new System.Drawing.Size(57, 19);
			this.txtFileOffset.Location = new System.Drawing.Point(184, 24);
			this.txtFileOffset.TabIndex = 5;
			this.txtFileOffset.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtFileOffset.AcceptsReturn = true;
			this.txtFileOffset.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtFileOffset.BackColor = System.Drawing.SystemColors.Window;
			this.txtFileOffset.CausesValidation = true;
			this.txtFileOffset.Enabled = true;
			this.txtFileOffset.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtFileOffset.HideSelection = true;
			this.txtFileOffset.ReadOnly = false;
			this.txtFileOffset.MaxLength = 0;
			this.txtFileOffset.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtFileOffset.Multiline = false;
			this.txtFileOffset.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtFileOffset.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtFileOffset.TabStop = true;
			this.txtFileOffset.Visible = true;
			this.txtFileOffset.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtFileOffset.Name = "txtFileOffset";
			this.txtHeight.AutoSize = false;
			this.txtHeight.Size = new System.Drawing.Size(129, 19);
			this.txtHeight.Location = new System.Drawing.Point(184, 96);
			this.txtHeight.TabIndex = 4;
			this.txtHeight.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtHeight.AcceptsReturn = true;
			this.txtHeight.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtHeight.BackColor = System.Drawing.SystemColors.Window;
			this.txtHeight.CausesValidation = true;
			this.txtHeight.Enabled = true;
			this.txtHeight.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtHeight.HideSelection = true;
			this.txtHeight.ReadOnly = false;
			this.txtHeight.MaxLength = 0;
			this.txtHeight.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtHeight.Multiline = false;
			this.txtHeight.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtHeight.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtHeight.TabStop = true;
			this.txtHeight.Visible = true;
			this.txtHeight.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtHeight.Name = "txtHeight";
			this.txtWidth.AutoSize = false;
			this.txtWidth.Size = new System.Drawing.Size(129, 19);
			this.txtWidth.Location = new System.Drawing.Point(184, 72);
			this.txtWidth.TabIndex = 3;
			this.txtWidth.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtWidth.AcceptsReturn = true;
			this.txtWidth.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtWidth.BackColor = System.Drawing.SystemColors.Window;
			this.txtWidth.CausesValidation = true;
			this.txtWidth.Enabled = true;
			this.txtWidth.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtWidth.HideSelection = true;
			this.txtWidth.ReadOnly = false;
			this.txtWidth.MaxLength = 0;
			this.txtWidth.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtWidth.Multiline = false;
			this.txtWidth.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtWidth.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtWidth.TabStop = true;
			this.txtWidth.Visible = true;
			this.txtWidth.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtWidth.Name = "txtWidth";
			this.txtBpT.AutoSize = false;
			this.txtBpT.Size = new System.Drawing.Size(73, 19);
			this.txtBpT.Location = new System.Drawing.Point(312, 120);
			this.txtBpT.ReadOnly = true;
			this.txtBpT.TabIndex = 2;
			this.txtBpT.Text = "1";
			this.txtBpT.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtBpT.AcceptsReturn = true;
			this.txtBpT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtBpT.BackColor = System.Drawing.SystemColors.Window;
			this.txtBpT.CausesValidation = true;
			this.txtBpT.Enabled = true;
			this.txtBpT.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtBpT.HideSelection = true;
			this.txtBpT.MaxLength = 0;
			this.txtBpT.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtBpT.Multiline = false;
			this.txtBpT.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtBpT.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtBpT.TabStop = true;
			this.txtBpT.Visible = true;
			this.txtBpT.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtBpT.Name = "txtBpT";
			this.upd.Size = new System.Drawing.Size(40, 19);
			this.upd.Location = new System.Drawing.Point(272, 120);
			this.upd.TabIndex = 1;
			this.upd.Text = "upd";
			this.upd.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.upd.BackColor = System.Drawing.Color.Red;
			this.upd.Name = "upd";
			this.Label2.Text = "File Offset";
			this.Label2.Size = new System.Drawing.Size(57, 17);
			this.Label2.Location = new System.Drawing.Point(120, 24);
			this.Label2.TabIndex = 15;
			this.Label2.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label2.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label2.BackColor = System.Drawing.SystemColors.Control;
			this.Label2.Enabled = true;
			this.Label2.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label2.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label2.UseMnemonic = true;
			this.Label2.Visible = true;
			this.Label2.AutoSize = false;
			this.Label2.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label2.Name = "Label2";
			this.Label3.Text = "Width";
			this.Label3.Size = new System.Drawing.Size(57, 17);
			this.Label3.Location = new System.Drawing.Point(120, 72);
			this.Label3.TabIndex = 14;
			this.Label3.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label3.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label3.BackColor = System.Drawing.SystemColors.Control;
			this.Label3.Enabled = true;
			this.Label3.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label3.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label3.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label3.UseMnemonic = true;
			this.Label3.Visible = true;
			this.Label3.AutoSize = false;
			this.Label3.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label3.Name = "Label3";
			this.Label8.Text = "Height";
			this.Label8.Size = new System.Drawing.Size(57, 17);
			this.Label8.Location = new System.Drawing.Point(120, 96);
			this.Label8.TabIndex = 13;
			this.Label8.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label8.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label8.BackColor = System.Drawing.SystemColors.Control;
			this.Label8.Enabled = true;
			this.Label8.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label8.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label8.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label8.UseMnemonic = true;
			this.Label8.Visible = true;
			this.Label8.AutoSize = false;
			this.Label8.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label8.Name = "Label8";
			this.Label9.Text = "Bytes / Tile (Recommend 1)";
			this.Label9.Size = new System.Drawing.Size(145, 17);
			this.Label9.Location = new System.Drawing.Point(120, 120);
			this.Label9.TabIndex = 12;
			this.Label9.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label9.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label9.BackColor = System.Drawing.SystemColors.Control;
			this.Label9.Enabled = true;
			this.Label9.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label9.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label9.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label9.UseMnemonic = true;
			this.Label9.Visible = true;
			this.Label9.AutoSize = false;
			this.Label9.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label9.Name = "Label9";
			this.Label5.Text = "Height";
			this.Label5.Size = new System.Drawing.Size(41, 17);
			this.Label5.Location = new System.Drawing.Point(24, 320);
			this.Label5.TabIndex = 29;
			this.Label5.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label5.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label5.BackColor = System.Drawing.SystemColors.Control;
			this.Label5.Enabled = true;
			this.Label5.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label5.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label5.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label5.UseMnemonic = true;
			this.Label5.Visible = true;
			this.Label5.AutoSize = false;
			this.Label5.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label5.Name = "Label5";
			this.Label4.Text = "Width";
			this.Label4.Size = new System.Drawing.Size(57, 17);
			this.Label4.Location = new System.Drawing.Point(24, 296);
			this.Label4.TabIndex = 28;
			this.Label4.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label4.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label4.BackColor = System.Drawing.SystemColors.Control;
			this.Label4.Enabled = true;
			this.Label4.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label4.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label4.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label4.UseMnemonic = true;
			this.Label4.Visible = true;
			this.Label4.AutoSize = false;
			this.Label4.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label4.Name = "Label4";
			this.Label1.Text = "Area Mappings";
			this.Label1.Size = new System.Drawing.Size(73, 17);
			this.Label1.Location = new System.Drawing.Point(8, 272);
			this.Label1.TabIndex = 27;
			this.Label1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label1.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label1.BackColor = System.Drawing.SystemColors.Control;
			this.Label1.Enabled = true;
			this.Label1.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label1.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label1.UseMnemonic = true;
			this.Label1.Visible = true;
			this.Label1.AutoSize = false;
			this.Label1.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label1.Name = "Label1";
			this.Controls.Add(txtAreaHeight);
			this.Controls.Add(txtAreaWidth);
			this.Controls.Add(Command1);
			this.Controls.Add(cmdCancel);
			this.Controls.Add(cmdOK);
			this.Controls.Add(Frame2);
			this.Controls.Add(Frame1);
			this.Controls.Add(Label5);
			this.Controls.Add(Label4);
			this.Controls.Add(Label1);
			this.Frame2.Controls.Add(_optTiles_3);
			this.Frame2.Controls.Add(_optTiles_4);
			this.Frame2.Controls.Add(_optTiles_0);
			this.Frame2.Controls.Add(_optTiles_1);
			this.Frame2.Controls.Add(_optTiles_2);
			this.Frame1.Controls.Add(chkAuto);
			this.Frame1.Controls.Add(_optType_1);
			this.Frame1.Controls.Add(_optType_2);
			this.Frame1.Controls.Add(_optType_3);
			this.Frame1.Controls.Add(_optType_5);
			this.Frame1.Controls.Add(_optType_4);
			this.Frame1.Controls.Add(_optType_6);
			this.Frame1.Controls.Add(txtFileOffset);
			this.Frame1.Controls.Add(txtHeight);
			this.Frame1.Controls.Add(txtWidth);
			this.Frame1.Controls.Add(txtBpT);
			this.Frame1.Controls.Add(upd);
			this.Frame1.Controls.Add(Label2);
			this.Frame1.Controls.Add(Label3);
			this.Frame1.Controls.Add(Label8);
			this.Frame1.Controls.Add(Label9);
			this.optTiles.SetIndex(_optTiles_3, ((short) (3)));
			this.optTiles.SetIndex(_optTiles_4, ((short) (4)));
			this.optTiles.SetIndex(_optTiles_0, ((short) (0)));
			this.optTiles.SetIndex(_optTiles_1, ((short) (1)));
			this.optTiles.SetIndex(_optTiles_2, ((short) (2)));
			this.optType.SetIndex(_optType_1, ((short) (1)));
			this.optType.SetIndex(_optType_2, ((short) (2)));
			this.optType.SetIndex(_optType_3, ((short) (3)));
			this.optType.SetIndex(_optType_5, ((short) (5)));
			this.optType.SetIndex(_optType_4, ((short) (4)));
			this.optType.SetIndex(_optType_6, ((short) (6)));
			((System.ComponentModel.ISupportInitialize) this.optType).EndInit();
			((System.ComponentModel.ISupportInitialize) this.optTiles).EndInit();
			this.Frame2.ResumeLayout(false);
			this.Frame1.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		#endregion
	}
}
