#define Win32
using System.Diagnostics;
using System;
using System.Windows.Forms;
using AxMSComCtl2;
using ERY.Xle;
using ERY.AgateLib;
using System.Drawing;
using Microsoft.VisualBasic;
using System.Collections;
using Microsoft.VisualBasic.Compatibility;
using System.Linq;
using System.IO;
using ERY.AgateLib.WinForms;

namespace XleMapEditor
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated()]public partial class frmSpecial
	{
		#region "Windows Form Designer generated code "
		[System.Diagnostics.DebuggerNonUserCode()]public frmSpecial()
		{
			//This call is required by the Windows Form Designer.
			InitializeComponent();
		}
		//Form overrides dispose to clean up the component list.
		[System.Diagnostics.DebuggerNonUserCode()]protected override void Dispose(bool Disposing)
		{
			if (Disposing)
			{
				if (components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose(Disposing);
		}
		//Required by the Windows Form Designer
		private System.ComponentModel.Container components = null;
		public System.Windows.Forms.ToolTip ToolTip1;
		public System.Windows.Forms.ComboBox cboDoorKey;
		public System.Windows.Forms.Label Label10;
		public System.Windows.Forms.GroupBox frmDoor;
		public System.Windows.Forms.TextBox txtGold;
		public System.Windows.Forms.RadioButton _optTreasure_1;
		public System.Windows.Forms.RadioButton _optTreasure_0;
		public System.Windows.Forms.ComboBox cboChestItem;
		public System.Windows.Forms.GroupBox frmChest;
		public System.Windows.Forms.RadioButton _optSpeakWith_2;
		public System.Windows.Forms.RadioButton _optSpeakWith_1;
		public System.Windows.Forms.GroupBox frmSpeakWith;
		public System.Windows.Forms.TextBox txtSpcHeight;
		public System.Windows.Forms.TextBox txtSpcWidth;
		public System.Windows.Forms.RadioButton _optType_25;
		public System.Windows.Forms.RadioButton _optType_24;
		public System.Windows.Forms.RadioButton _optType_23;
		public System.Windows.Forms.RadioButton _optType_22;
		public System.Windows.Forms.RadioButton _optType_1;
		public System.Windows.Forms.RadioButton _optType_2;
		public System.Windows.Forms.RadioButton _optType_20;
		public System.Windows.Forms.RadioButton _optType_21;
		public System.Windows.Forms.GroupBox Frame1;
		public System.Windows.Forms.TextBox txtLocY;
		public System.Windows.Forms.TextBox txtLocX;
		public System.Windows.Forms.CheckBox chkAutoChange;
		public System.Windows.Forms.TextBox txtNewX;
		public System.Windows.Forms.TextBox txtNewY;
		public System.Windows.Forms.TextBox txtNewMap;
		public System.Windows.Forms.Label Label2;
		public System.Windows.Forms.Label Label3;
		public System.Windows.Forms.Label Label4;
		public System.Windows.Forms.GroupBox frmMapChange;
		public System.Windows.Forms.Button cmdCancel;
		public System.Windows.Forms.Button cmdOK;
		public System.Windows.Forms.RadioButton _optStoreType_15;
		public System.Windows.Forms.RadioButton _optStoreType_14;
		public System.Windows.Forms.RadioButton _optStoreType_0;
		public System.Windows.Forms.RadioButton _optStoreType_9;
		public System.Windows.Forms.RadioButton _optStoreType_8;
		public System.Windows.Forms.RadioButton _optStoreType_7;
		public System.Windows.Forms.RadioButton _optStoreType_6;
		public System.Windows.Forms.RadioButton _optStoreType_5;
		public System.Windows.Forms.RadioButton _optStoreType_4;
		public System.Windows.Forms.RadioButton _optStoreType_2;
		public System.Windows.Forms.RadioButton _optStoreType_1;
		public System.Windows.Forms.RadioButton _optStoreType_3;
		public System.Windows.Forms.RadioButton _optStoreType_10;
		public System.Windows.Forms.TextBox txtName;
		public System.Windows.Forms.TextBox txtPrice;
		public System.Windows.Forms.RadioButton _optStoreType_11;
		public System.Windows.Forms.RadioButton _optStoreType_12;
		public System.Windows.Forms.RadioButton _optStoreType_13;
		public System.Windows.Forms.Label Label8;
		public System.Windows.Forms.Label Label6;
		public System.Windows.Forms.GroupBox frmStore;
		public System.Windows.Forms.Label Label9;
		public System.Windows.Forms.Label Label1;
		public System.Windows.Forms.Label lblSpecialData;
		public System.Windows.Forms.Label Label5;
		public System.Windows.Forms.Label Label7;
		public Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray optSpeakWith;
		public Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray optStoreType;
		public Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray optTreasure;
		public Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray optType;
		//NOTE: The following procedure is required by the Windows Form Designer
		//It can be modified using the Windows Form Designer.
		//Do not modify it using the code editor.
		[System.Diagnostics.DebuggerStepThrough()]private void InitializeComponent()
		{
			System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(frmSpecial));
			this.components = new System.ComponentModel.Container();
			base.Load += new System.EventHandler(frmSpecial_Load);
			base.Paint += new System.Windows.Forms.PaintEventHandler(frmSpecial_Paint);
			this.ToolTip1 = new System.Windows.Forms.ToolTip(components);
			this.frmDoor = new System.Windows.Forms.GroupBox();
			this.cboDoorKey = new System.Windows.Forms.ComboBox();
			this.cboDoorKey.TextChanged += new System.EventHandler(cboDoorKey_TextChanged);
			this.cboDoorKey.SelectedIndexChanged += new System.EventHandler(cboDoorKey_SelectedIndexChanged);
			this.cboDoorKey.Leave += new System.EventHandler(cboDoorKey_Leave);
			this.Label10 = new System.Windows.Forms.Label();
			this.frmChest = new System.Windows.Forms.GroupBox();
			this.txtGold = new System.Windows.Forms.TextBox();
			this.txtGold.TextChanged += new System.EventHandler(txtGold_TextChanged);
			this._optTreasure_1 = new System.Windows.Forms.RadioButton();
			this._optTreasure_0 = new System.Windows.Forms.RadioButton();
			this.cboChestItem = new System.Windows.Forms.ComboBox();
			this.cboChestItem.TextChanged += new System.EventHandler(cboChestItem_TextChanged);
			this.cboChestItem.SelectedIndexChanged += new System.EventHandler(cboChestItem_SelectedIndexChanged);
			this.cboChestItem.Leave += new System.EventHandler(cboChestItem_Leave);
			this.frmSpeakWith = new System.Windows.Forms.GroupBox();
			this._optSpeakWith_2 = new System.Windows.Forms.RadioButton();
			this._optSpeakWith_1 = new System.Windows.Forms.RadioButton();
			this.txtSpcHeight = new System.Windows.Forms.TextBox();
			this.txtSpcWidth = new System.Windows.Forms.TextBox();
			this.Frame1 = new System.Windows.Forms.GroupBox();
			this._optType_25 = new System.Windows.Forms.RadioButton();
			this._optType_24 = new System.Windows.Forms.RadioButton();
			this._optType_23 = new System.Windows.Forms.RadioButton();
			this._optType_22 = new System.Windows.Forms.RadioButton();
			this._optType_1 = new System.Windows.Forms.RadioButton();
			this._optType_2 = new System.Windows.Forms.RadioButton();
			this._optType_20 = new System.Windows.Forms.RadioButton();
			this._optType_21 = new System.Windows.Forms.RadioButton();
			this.txtLocY = new System.Windows.Forms.TextBox();
			this.txtLocX = new System.Windows.Forms.TextBox();
			this.frmMapChange = new System.Windows.Forms.GroupBox();
			this.chkAutoChange = new System.Windows.Forms.CheckBox();
			this.chkAutoChange.CheckStateChanged += new System.EventHandler(chkAutoChange_CheckStateChanged);
			this.txtNewX = new System.Windows.Forms.TextBox();
			this.txtNewX.Leave += new System.EventHandler(txtNewX_Leave);
			this.txtNewY = new System.Windows.Forms.TextBox();
			this.txtNewY.Leave += new System.EventHandler(txtNewY_Leave);
			this.txtNewMap = new System.Windows.Forms.TextBox();
			this.txtNewMap.Leave += new System.EventHandler(txtNewMap_Leave);
			this.Label2 = new System.Windows.Forms.Label();
			this.Label3 = new System.Windows.Forms.Label();
			this.Label4 = new System.Windows.Forms.Label();
			this.cmdCancel = new System.Windows.Forms.Button();
			this.cmdCancel.Click += new System.EventHandler(cmdCancel_Click);
			this.cmdOK = new System.Windows.Forms.Button();
			this.cmdOK.Click += new System.EventHandler(cmdOK_Click);
			this.frmStore = new System.Windows.Forms.GroupBox();
			this._optStoreType_15 = new System.Windows.Forms.RadioButton();
			this._optStoreType_14 = new System.Windows.Forms.RadioButton();
			this._optStoreType_0 = new System.Windows.Forms.RadioButton();
			this._optStoreType_9 = new System.Windows.Forms.RadioButton();
			this._optStoreType_8 = new System.Windows.Forms.RadioButton();
			this._optStoreType_7 = new System.Windows.Forms.RadioButton();
			this._optStoreType_6 = new System.Windows.Forms.RadioButton();
			this._optStoreType_5 = new System.Windows.Forms.RadioButton();
			this._optStoreType_4 = new System.Windows.Forms.RadioButton();
			this._optStoreType_2 = new System.Windows.Forms.RadioButton();
			this._optStoreType_1 = new System.Windows.Forms.RadioButton();
			this._optStoreType_3 = new System.Windows.Forms.RadioButton();
			this._optStoreType_10 = new System.Windows.Forms.RadioButton();
			this.txtName = new System.Windows.Forms.TextBox();
			this.txtName.TextChanged += new System.EventHandler(txtName_TextChanged);
			this.txtName.Leave += new System.EventHandler(txtName_Leave);
			this.txtPrice = new System.Windows.Forms.TextBox();
			this.txtPrice.TextChanged += new System.EventHandler(txtPrice_TextChanged);
			this._optStoreType_11 = new System.Windows.Forms.RadioButton();
			this._optStoreType_12 = new System.Windows.Forms.RadioButton();
			this._optStoreType_13 = new System.Windows.Forms.RadioButton();
			this.Label8 = new System.Windows.Forms.Label();
			this.Label6 = new System.Windows.Forms.Label();
			this.Label9 = new System.Windows.Forms.Label();
			this.Label1 = new System.Windows.Forms.Label();
			this.lblSpecialData = new System.Windows.Forms.Label();
			this.Label5 = new System.Windows.Forms.Label();
			this.Label7 = new System.Windows.Forms.Label();
			this.optSpeakWith = new Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray(components);
			this.optSpeakWith.CheckedChanged += new System.EventHandler(optSpeakWith_CheckedChanged);
			this.optStoreType = new Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray(components);
			this.optTreasure = new Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray(components);
			this.optTreasure.CheckedChanged += new System.EventHandler(optTreasure_CheckedChanged);
			this.optType = new Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray(components);
			this.optType.CheckedChanged += new System.EventHandler(optType_CheckedChanged);
			this.frmDoor.SuspendLayout();
			this.frmChest.SuspendLayout();
			this.frmSpeakWith.SuspendLayout();
			this.Frame1.SuspendLayout();
			this.frmMapChange.SuspendLayout();
			this.frmStore.SuspendLayout();
			this.SuspendLayout();
			this.ToolTip1.Active = true;
			((System.ComponentModel.ISupportInitialize) this.optSpeakWith).BeginInit();
			((System.ComponentModel.ISupportInitialize) this.optStoreType).BeginInit();
			((System.ComponentModel.ISupportInitialize) this.optTreasure).BeginInit();
			((System.ComponentModel.ISupportInitialize) this.optType).BeginInit();
			this.Text = "Form2";
			this.ClientSize = new System.Drawing.Size(522, 409);
			this.Location = new System.Drawing.Point(4, 23);
			this.StartPosition = System.Windows.Forms.FormStartPosition.WindowsDefaultLocation;
			this.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.SystemColors.Control;
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
			this.ControlBox = true;
			this.Enabled = true;
			this.KeyPreview = false;
			this.MaximizeBox = true;
			this.MinimizeBox = true;
			this.Cursor = System.Windows.Forms.Cursors.Default;
			this.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.ShowInTaskbar = true;
			this.HelpButton = false;
			this.WindowState = System.Windows.Forms.FormWindowState.Normal;
			this.Name = "frmSpecial";
			this.frmDoor.Text = "Door";
			this.frmDoor.Size = new System.Drawing.Size(201, 89);
			this.frmDoor.Location = new System.Drawing.Point(192, 8);
			this.frmDoor.TabIndex = 55;
			this.frmDoor.Visible = false;
			this.frmDoor.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.frmDoor.BackColor = System.Drawing.SystemColors.Control;
			this.frmDoor.Enabled = true;
			this.frmDoor.ForeColor = System.Drawing.SystemColors.ControlText;
			this.frmDoor.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.frmDoor.Name = "frmDoor";
			this.cboDoorKey.Size = new System.Drawing.Size(137, 21);
			this.cboDoorKey.Location = new System.Drawing.Point(40, 24);
			this.cboDoorKey.Items.AddRange(new object[] {"Iron Key", "Copper Key", "Brass Key", "Stone Key"});
			this.cboDoorKey.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboDoorKey.TabIndex = 57;
			this.cboDoorKey.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.cboDoorKey.BackColor = System.Drawing.SystemColors.Window;
			this.cboDoorKey.CausesValidation = true;
			this.cboDoorKey.Enabled = true;
			this.cboDoorKey.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboDoorKey.IntegralHeight = true;
			this.cboDoorKey.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboDoorKey.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboDoorKey.Sorted = false;
			this.cboDoorKey.TabStop = true;
			this.cboDoorKey.Visible = true;
			this.cboDoorKey.Name = "cboDoorKey";
			this.Label10.Text = "Key:";
			this.Label10.Size = new System.Drawing.Size(65, 17);
			this.Label10.Location = new System.Drawing.Point(8, 24);
			this.Label10.TabIndex = 56;
			this.Label10.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label10.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label10.BackColor = System.Drawing.SystemColors.Control;
			this.Label10.Enabled = true;
			this.Label10.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label10.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label10.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label10.UseMnemonic = true;
			this.Label10.Visible = true;
			this.Label10.AutoSize = false;
			this.Label10.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label10.Name = "Label10";
			this.frmChest.Text = "Treasure Chest";
			this.frmChest.Size = new System.Drawing.Size(289, 89);
			this.frmChest.Location = new System.Drawing.Point(192, 8);
			this.frmChest.TabIndex = 49;
			this.frmChest.Visible = false;
			this.frmChest.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.frmChest.BackColor = System.Drawing.SystemColors.Control;
			this.frmChest.Enabled = true;
			this.frmChest.ForeColor = System.Drawing.SystemColors.ControlText;
			this.frmChest.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.frmChest.Name = "frmChest";
			this.txtGold.AutoSize = false;
			this.txtGold.Enabled = false;
			this.txtGold.Size = new System.Drawing.Size(97, 19);
			this.txtGold.Location = new System.Drawing.Point(72, 48);
			this.txtGold.TabIndex = 53;
			this.txtGold.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtGold.AcceptsReturn = true;
			this.txtGold.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtGold.BackColor = System.Drawing.SystemColors.Window;
			this.txtGold.CausesValidation = true;
			this.txtGold.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtGold.HideSelection = true;
			this.txtGold.ReadOnly = false;
			this.txtGold.MaxLength = 0;
			this.txtGold.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtGold.Multiline = false;
			this.txtGold.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtGold.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtGold.TabStop = true;
			this.txtGold.Visible = true;
			this.txtGold.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtGold.Name = "txtGold";
			this._optTreasure_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTreasure_1.Text = "Gold:";
			this._optTreasure_1.Size = new System.Drawing.Size(49, 17);
			this._optTreasure_1.Location = new System.Drawing.Point(16, 48);
			this._optTreasure_1.TabIndex = 52;
			this._optTreasure_1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optTreasure_1.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTreasure_1.BackColor = System.Drawing.SystemColors.Control;
			this._optTreasure_1.CausesValidation = true;
			this._optTreasure_1.Enabled = true;
			this._optTreasure_1.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optTreasure_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._optTreasure_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optTreasure_1.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optTreasure_1.TabStop = true;
			this._optTreasure_1.Checked = false;
			this._optTreasure_1.Visible = true;
			this._optTreasure_1.Name = "_optTreasure_1";
			this._optTreasure_0.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTreasure_0.Text = "Item:";
			this._optTreasure_0.Size = new System.Drawing.Size(49, 17);
			this._optTreasure_0.Location = new System.Drawing.Point(16, 24);
			this._optTreasure_0.TabIndex = 51;
			this._optTreasure_0.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optTreasure_0.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optTreasure_0.BackColor = System.Drawing.SystemColors.Control;
			this._optTreasure_0.CausesValidation = true;
			this._optTreasure_0.Enabled = true;
			this._optTreasure_0.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optTreasure_0.Cursor = System.Windows.Forms.Cursors.Default;
			this._optTreasure_0.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optTreasure_0.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optTreasure_0.TabStop = true;
			this._optTreasure_0.Checked = false;
			this._optTreasure_0.Visible = true;
			this._optTreasure_0.Name = "_optTreasure_0";
			this.cboChestItem.Enabled = false;
			this.cboChestItem.Size = new System.Drawing.Size(153, 21);
			this.cboChestItem.Location = new System.Drawing.Point(72, 24);
			this.cboChestItem.Items.AddRange(new object[] {"Gold Armband", "Climbing Gear", "Healing Herbs", "Iron Key", "Copper Key", "Brass Key", "Stone Key", "Magic Seeds", "Mail -", "Tulip", "Compass", "Magic Ice", "Scepter", "Guard Jewel", "Compendium", "Crown", "Jade Coin", "Topaz Coin", "Amethyst Coin", "Sapphire Coin", "Turquoise Coin", "Ruby Coin", "Diamond Coin"});
			this.cboChestItem.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboChestItem.TabIndex = 50;
			this.cboChestItem.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.cboChestItem.BackColor = System.Drawing.SystemColors.Window;
			this.cboChestItem.CausesValidation = true;
			this.cboChestItem.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboChestItem.IntegralHeight = true;
			this.cboChestItem.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboChestItem.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboChestItem.Sorted = false;
			this.cboChestItem.TabStop = true;
			this.cboChestItem.Visible = true;
			this.cboChestItem.Name = "cboChestItem";
			this.frmSpeakWith.Text = "Speak With";
			this.frmSpeakWith.Size = new System.Drawing.Size(249, 137);
			this.frmSpeakWith.Location = new System.Drawing.Point(192, 8);
			this.frmSpeakWith.TabIndex = 46;
			this.frmSpeakWith.Visible = false;
			this.frmSpeakWith.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.frmSpeakWith.BackColor = System.Drawing.SystemColors.Control;
			this.frmSpeakWith.Enabled = true;
			this.frmSpeakWith.ForeColor = System.Drawing.SystemColors.ControlText;
			this.frmSpeakWith.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.frmSpeakWith.Name = "frmSpeakWith";
			this._optSpeakWith_2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optSpeakWith_2.Text = "Wizard of Potions";
			this._optSpeakWith_2.Size = new System.Drawing.Size(153, 17);
			this._optSpeakWith_2.Location = new System.Drawing.Point(16, 48);
			this._optSpeakWith_2.TabIndex = 59;
			this._optSpeakWith_2.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optSpeakWith_2.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optSpeakWith_2.BackColor = System.Drawing.SystemColors.Control;
			this._optSpeakWith_2.CausesValidation = true;
			this._optSpeakWith_2.Enabled = true;
			this._optSpeakWith_2.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optSpeakWith_2.Cursor = System.Windows.Forms.Cursors.Default;
			this._optSpeakWith_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optSpeakWith_2.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optSpeakWith_2.TabStop = true;
			this._optSpeakWith_2.Checked = false;
			this._optSpeakWith_2.Visible = true;
			this._optSpeakWith_2.Name = "_optSpeakWith_2";
			this._optSpeakWith_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optSpeakWith_1.Text = "Cassandra";
			this._optSpeakWith_1.Size = new System.Drawing.Size(89, 17);
			this._optSpeakWith_1.Location = new System.Drawing.Point(16, 24);
			this._optSpeakWith_1.TabIndex = 47;
			this._optSpeakWith_1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optSpeakWith_1.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optSpeakWith_1.BackColor = System.Drawing.SystemColors.Control;
			this._optSpeakWith_1.CausesValidation = true;
			this._optSpeakWith_1.Enabled = true;
			this._optSpeakWith_1.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optSpeakWith_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._optSpeakWith_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optSpeakWith_1.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optSpeakWith_1.TabStop = true;
			this._optSpeakWith_1.Checked = false;
			this._optSpeakWith_1.Visible = true;
			this._optSpeakWith_1.Name = "_optSpeakWith_1";
			this.txtSpcHeight.AutoSize = false;
			this.txtSpcHeight.Size = new System.Drawing.Size(81, 19);
			this.txtSpcHeight.Location = new System.Drawing.Point(96, 104);
			this.txtSpcHeight.TabIndex = 41;
			this.txtSpcHeight.Text = "1";
			this.txtSpcHeight.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtSpcHeight.AcceptsReturn = true;
			this.txtSpcHeight.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtSpcHeight.BackColor = System.Drawing.SystemColors.Window;
			this.txtSpcHeight.CausesValidation = true;
			this.txtSpcHeight.Enabled = true;
			this.txtSpcHeight.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtSpcHeight.HideSelection = true;
			this.txtSpcHeight.ReadOnly = false;
			this.txtSpcHeight.MaxLength = 0;
			this.txtSpcHeight.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtSpcHeight.Multiline = false;
			this.txtSpcHeight.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtSpcHeight.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtSpcHeight.TabStop = true;
			this.txtSpcHeight.Visible = true;
			this.txtSpcHeight.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtSpcHeight.Name = "txtSpcHeight";
			this.txtSpcWidth.AutoSize = false;
			this.txtSpcWidth.Size = new System.Drawing.Size(81, 19);
			this.txtSpcWidth.Location = new System.Drawing.Point(96, 80);
			this.txtSpcWidth.TabIndex = 40;
			this.txtSpcWidth.Text = "1";
			this.txtSpcWidth.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtSpcWidth.AcceptsReturn = true;
			this.txtSpcWidth.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtSpcWidth.BackColor = System.Drawing.SystemColors.Window;
			this.txtSpcWidth.CausesValidation = true;
			this.txtSpcWidth.Enabled = true;
			this.txtSpcWidth.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtSpcWidth.HideSelection = true;
			this.txtSpcWidth.ReadOnly = false;
			this.txtSpcWidth.MaxLength = 0;
			this.txtSpcWidth.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtSpcWidth.Multiline = false;
			this.txtSpcWidth.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtSpcWidth.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtSpcWidth.TabStop = true;
			this.txtSpcWidth.Visible = true;
			this.txtSpcWidth.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtSpcWidth.Name = "txtSpcWidth";
			this.Frame1.Text = "Select Special Event Type";
			this.Frame1.Size = new System.Drawing.Size(177, 217);
			this.Frame1.Location = new System.Drawing.Point(8, 184);
			this.Frame1.TabIndex = 33;
			this.Frame1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Frame1.BackColor = System.Drawing.SystemColors.Control;
			this.Frame1.Enabled = true;
			this.Frame1.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Frame1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Frame1.Visible = true;
			this.Frame1.Name = "Frame1";
			this._optType_25.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_25.Text = "Take";
			this._optType_25.Size = new System.Drawing.Size(137, 13);
			this._optType_25.Location = new System.Drawing.Point(8, 184);
			this._optType_25.TabIndex = 58;
			this._optType_25.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_25.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_25.BackColor = System.Drawing.SystemColors.Control;
			this._optType_25.CausesValidation = true;
			this._optType_25.Enabled = true;
			this._optType_25.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_25.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_25.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_25.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_25.TabStop = true;
			this._optType_25.Checked = false;
			this._optType_25.Visible = true;
			this._optType_25.Name = "_optType_25";
			this._optType_24.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_24.Text = "Door";
			this._optType_24.Size = new System.Drawing.Size(121, 13);
			this._optType_24.Location = new System.Drawing.Point(8, 160);
			this._optType_24.TabIndex = 54;
			this._optType_24.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_24.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_24.BackColor = System.Drawing.SystemColors.Control;
			this._optType_24.CausesValidation = true;
			this._optType_24.Enabled = true;
			this._optType_24.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_24.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_24.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_24.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_24.TabStop = true;
			this._optType_24.Checked = false;
			this._optType_24.Visible = true;
			this._optType_24.Name = "_optType_24";
			this._optType_23.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_23.Text = "Treasure Chest";
			this._optType_23.Size = new System.Drawing.Size(121, 13);
			this._optType_23.Location = new System.Drawing.Point(8, 136);
			this._optType_23.TabIndex = 48;
			this._optType_23.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_23.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_23.BackColor = System.Drawing.SystemColors.Control;
			this._optType_23.CausesValidation = true;
			this._optType_23.Enabled = true;
			this._optType_23.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_23.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_23.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_23.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_23.TabStop = true;
			this._optType_23.Checked = false;
			this._optType_23.Visible = true;
			this._optType_23.Name = "_optType_23";
			this._optType_22.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_22.Text = "Magic Ice";
			this._optType_22.Size = new System.Drawing.Size(161, 13);
			this._optType_22.Location = new System.Drawing.Point(8, 112);
			this._optType_22.TabIndex = 44;
			this._optType_22.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_22.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_22.BackColor = System.Drawing.SystemColors.Control;
			this._optType_22.CausesValidation = true;
			this._optType_22.Enabled = true;
			this._optType_22.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_22.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_22.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_22.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_22.TabStop = true;
			this._optType_22.Checked = false;
			this._optType_22.Visible = true;
			this._optType_22.Name = "_optType_22";
			this._optType_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_1.Text = "Map Change";
			this._optType_1.Size = new System.Drawing.Size(160, 17);
			this._optType_1.Location = new System.Drawing.Point(8, 24);
			this._optType_1.TabIndex = 2;
			this._optType_1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_1.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_1.BackColor = System.Drawing.SystemColors.Control;
			this._optType_1.CausesValidation = true;
			this._optType_1.Enabled = true;
			this._optType_1.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_1.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_1.TabStop = true;
			this._optType_1.Checked = false;
			this._optType_1.Visible = true;
			this._optType_1.Name = "_optType_1";
			this._optType_2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_2.Text = "Store";
			this._optType_2.Size = new System.Drawing.Size(160, 17);
			this._optType_2.Location = new System.Drawing.Point(8, 46);
			this._optType_2.TabIndex = 3;
			this._optType_2.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_2.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_2.BackColor = System.Drawing.SystemColors.Control;
			this._optType_2.CausesValidation = true;
			this._optType_2.Enabled = true;
			this._optType_2.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_2.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_2.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_2.TabStop = true;
			this._optType_2.Checked = false;
			this._optType_2.Visible = true;
			this._optType_2.Name = "_optType_2";
			this._optType_20.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_20.Text = "Teleport";
			this._optType_20.Size = new System.Drawing.Size(160, 17);
			this._optType_20.Location = new System.Drawing.Point(8, 67);
			this._optType_20.TabIndex = 4;
			this._optType_20.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_20.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_20.BackColor = System.Drawing.SystemColors.Control;
			this._optType_20.CausesValidation = true;
			this._optType_20.Enabled = true;
			this._optType_20.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_20.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_20.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_20.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_20.TabStop = true;
			this._optType_20.Checked = false;
			this._optType_20.Visible = true;
			this._optType_20.Name = "_optType_20";
			this._optType_21.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_21.Text = "Special Conversation";
			this._optType_21.Size = new System.Drawing.Size(160, 17);
			this._optType_21.Location = new System.Drawing.Point(8, 88);
			this._optType_21.TabIndex = 5;
			this._optType_21.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optType_21.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optType_21.BackColor = System.Drawing.SystemColors.Control;
			this._optType_21.CausesValidation = true;
			this._optType_21.Enabled = true;
			this._optType_21.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optType_21.Cursor = System.Windows.Forms.Cursors.Default;
			this._optType_21.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optType_21.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optType_21.TabStop = true;
			this._optType_21.Checked = false;
			this._optType_21.Visible = true;
			this._optType_21.Name = "_optType_21";
			this.txtLocY.AutoSize = false;
			this.txtLocY.Size = new System.Drawing.Size(81, 19);
			this.txtLocY.Location = new System.Drawing.Point(96, 48);
			this.txtLocY.TabIndex = 1;
			this.txtLocY.Text = "Text2";
			this.txtLocY.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtLocY.AcceptsReturn = true;
			this.txtLocY.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtLocY.BackColor = System.Drawing.SystemColors.Window;
			this.txtLocY.CausesValidation = true;
			this.txtLocY.Enabled = true;
			this.txtLocY.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtLocY.HideSelection = true;
			this.txtLocY.ReadOnly = false;
			this.txtLocY.MaxLength = 0;
			this.txtLocY.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtLocY.Multiline = false;
			this.txtLocY.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtLocY.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtLocY.TabStop = true;
			this.txtLocY.Visible = true;
			this.txtLocY.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtLocY.Name = "txtLocY";
			this.txtLocX.AutoSize = false;
			this.txtLocX.Size = new System.Drawing.Size(81, 19);
			this.txtLocX.Location = new System.Drawing.Point(96, 24);
			this.txtLocX.TabIndex = 0;
			this.txtLocX.Text = "txtLocX";
			this.txtLocX.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtLocX.AcceptsReturn = true;
			this.txtLocX.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtLocX.BackColor = System.Drawing.SystemColors.Window;
			this.txtLocX.CausesValidation = true;
			this.txtLocX.Enabled = true;
			this.txtLocX.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtLocX.HideSelection = true;
			this.txtLocX.ReadOnly = false;
			this.txtLocX.MaxLength = 0;
			this.txtLocX.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtLocX.Multiline = false;
			this.txtLocX.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtLocX.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtLocX.TabStop = true;
			this.txtLocX.Visible = true;
			this.txtLocX.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtLocX.Name = "txtLocX";
			this.frmMapChange.Text = "Map Change";
			this.frmMapChange.Size = new System.Drawing.Size(177, 129);
			this.frmMapChange.Location = new System.Drawing.Point(192, 8);
			this.frmMapChange.TabIndex = 26;
			this.frmMapChange.Visible = false;
			this.frmMapChange.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.frmMapChange.BackColor = System.Drawing.SystemColors.Control;
			this.frmMapChange.Enabled = true;
			this.frmMapChange.ForeColor = System.Drawing.SystemColors.ControlText;
			this.frmMapChange.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.frmMapChange.Name = "frmMapChange";
			this.chkAutoChange.Text = "Change without asking";
			this.chkAutoChange.Size = new System.Drawing.Size(161, 17);
			this.chkAutoChange.Location = new System.Drawing.Point(8, 104);
			this.chkAutoChange.TabIndex = 43;
			this.chkAutoChange.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.chkAutoChange.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.chkAutoChange.FlatStyle = System.Windows.Forms.FlatStyle.Standard;
			this.chkAutoChange.BackColor = System.Drawing.SystemColors.Control;
			this.chkAutoChange.CausesValidation = true;
			this.chkAutoChange.Enabled = true;
			this.chkAutoChange.ForeColor = System.Drawing.SystemColors.ControlText;
			this.chkAutoChange.Cursor = System.Windows.Forms.Cursors.Default;
			this.chkAutoChange.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.chkAutoChange.Appearance = System.Windows.Forms.Appearance.Normal;
			this.chkAutoChange.TabStop = true;
			this.chkAutoChange.CheckState = System.Windows.Forms.CheckState.Unchecked;
			this.chkAutoChange.Visible = true;
			this.chkAutoChange.Name = "chkAutoChange";
			this.txtNewX.AutoSize = false;
			this.txtNewX.Size = new System.Drawing.Size(97, 19);
			this.txtNewX.Location = new System.Drawing.Point(64, 48);
			this.txtNewX.TabIndex = 7;
			this.txtNewX.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtNewX.AcceptsReturn = true;
			this.txtNewX.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtNewX.BackColor = System.Drawing.SystemColors.Window;
			this.txtNewX.CausesValidation = true;
			this.txtNewX.Enabled = true;
			this.txtNewX.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtNewX.HideSelection = true;
			this.txtNewX.ReadOnly = false;
			this.txtNewX.MaxLength = 0;
			this.txtNewX.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtNewX.Multiline = false;
			this.txtNewX.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtNewX.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtNewX.TabStop = true;
			this.txtNewX.Visible = true;
			this.txtNewX.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtNewX.Name = "txtNewX";
			this.txtNewY.AutoSize = false;
			this.txtNewY.Size = new System.Drawing.Size(97, 19);
			this.txtNewY.Location = new System.Drawing.Point(64, 72);
			this.txtNewY.TabIndex = 8;
			this.txtNewY.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtNewY.AcceptsReturn = true;
			this.txtNewY.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtNewY.BackColor = System.Drawing.SystemColors.Window;
			this.txtNewY.CausesValidation = true;
			this.txtNewY.Enabled = true;
			this.txtNewY.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtNewY.HideSelection = true;
			this.txtNewY.ReadOnly = false;
			this.txtNewY.MaxLength = 0;
			this.txtNewY.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtNewY.Multiline = false;
			this.txtNewY.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtNewY.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtNewY.TabStop = true;
			this.txtNewY.Visible = true;
			this.txtNewY.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtNewY.Name = "txtNewY";
			this.txtNewMap.AutoSize = false;
			this.txtNewMap.Size = new System.Drawing.Size(97, 19);
			this.txtNewMap.Location = new System.Drawing.Point(64, 24);
			this.txtNewMap.TabIndex = 6;
			this.txtNewMap.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtNewMap.AcceptsReturn = true;
			this.txtNewMap.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtNewMap.BackColor = System.Drawing.SystemColors.Window;
			this.txtNewMap.CausesValidation = true;
			this.txtNewMap.Enabled = true;
			this.txtNewMap.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtNewMap.HideSelection = true;
			this.txtNewMap.ReadOnly = false;
			this.txtNewMap.MaxLength = 0;
			this.txtNewMap.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtNewMap.Multiline = false;
			this.txtNewMap.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtNewMap.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtNewMap.TabStop = true;
			this.txtNewMap.Visible = true;
			this.txtNewMap.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtNewMap.Name = "txtNewMap";
			this.Label2.Text = "X";
			this.Label2.Size = new System.Drawing.Size(49, 17);
			this.Label2.Location = new System.Drawing.Point(8, 48);
			this.Label2.TabIndex = 31;
			this.Label2.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label2.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label2.BackColor = System.Drawing.SystemColors.Control;
			this.Label2.Enabled = true;
			this.Label2.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label2.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label2.UseMnemonic = true;
			this.Label2.Visible = true;
			this.Label2.AutoSize = false;
			this.Label2.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label2.Name = "Label2";
			this.Label3.Text = "Y";
			this.Label3.Size = new System.Drawing.Size(49, 17);
			this.Label3.Location = new System.Drawing.Point(8, 72);
			this.Label3.TabIndex = 30;
			this.Label3.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label3.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label3.BackColor = System.Drawing.SystemColors.Control;
			this.Label3.Enabled = true;
			this.Label3.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label3.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label3.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label3.UseMnemonic = true;
			this.Label3.Visible = true;
			this.Label3.AutoSize = false;
			this.Label3.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label3.Name = "Label3";
			this.Label4.Text = "New Map";
			this.Label4.Size = new System.Drawing.Size(73, 17);
			this.Label4.Location = new System.Drawing.Point(8, 24);
			this.Label4.TabIndex = 28;
			this.Label4.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label4.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label4.BackColor = System.Drawing.SystemColors.Control;
			this.Label4.Enabled = true;
			this.Label4.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label4.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label4.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label4.UseMnemonic = true;
			this.Label4.Visible = true;
			this.Label4.AutoSize = false;
			this.Label4.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label4.Name = "Label4";
			this.cmdCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.CancelButton = this.cmdCancel;
			this.cmdCancel.Text = "Cancel";
			this.cmdCancel.Size = new System.Drawing.Size(81, 25);
			this.cmdCancel.Location = new System.Drawing.Point(352, 376);
			this.cmdCancel.TabIndex = 36;
			this.cmdCancel.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.cmdCancel.BackColor = System.Drawing.SystemColors.Control;
			this.cmdCancel.CausesValidation = true;
			this.cmdCancel.Enabled = true;
			this.cmdCancel.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdCancel.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdCancel.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdCancel.TabStop = true;
			this.cmdCancel.Name = "cmdCancel";
			this.cmdOK.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmdOK.Text = "OK";
			this.AcceptButton = this.cmdOK;
			this.cmdOK.Size = new System.Drawing.Size(73, 25);
			this.cmdOK.Location = new System.Drawing.Point(440, 376);
			this.cmdOK.TabIndex = 37;
			this.cmdOK.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.cmdOK.BackColor = System.Drawing.SystemColors.Control;
			this.cmdOK.CausesValidation = true;
			this.cmdOK.Enabled = true;
			this.cmdOK.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdOK.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdOK.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdOK.TabStop = true;
			this.cmdOK.Name = "cmdOK";
			this.frmStore.Text = "Store";
			this.frmStore.Size = new System.Drawing.Size(321, 297);
			this.frmStore.Location = new System.Drawing.Point(192, 8);
			this.frmStore.TabIndex = 9;
			this.frmStore.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.frmStore.BackColor = System.Drawing.SystemColors.Control;
			this.frmStore.Enabled = true;
			this.frmStore.ForeColor = System.Drawing.SystemColors.ControlText;
			this.frmStore.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.frmStore.Visible = true;
			this.frmStore.Name = "frmStore";
			this._optStoreType_15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_15.Text = "Magic";
			this._optStoreType_15.Size = new System.Drawing.Size(113, 17);
			this._optStoreType_15.Location = new System.Drawing.Point(152, 192);
			this._optStoreType_15.TabIndex = 45;
			this._optStoreType_15.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_15.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_15.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_15.CausesValidation = true;
			this._optStoreType_15.Enabled = true;
			this._optStoreType_15.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_15.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_15.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_15.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_15.TabStop = true;
			this._optStoreType_15.Checked = false;
			this._optStoreType_15.Visible = true;
			this._optStoreType_15.Name = "_optStoreType_15";
			this._optStoreType_14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_14.Text = "Vault";
			this._optStoreType_14.Size = new System.Drawing.Size(153, 17);
			this._optStoreType_14.Location = new System.Drawing.Point(152, 168);
			this._optStoreType_14.TabIndex = 42;
			this._optStoreType_14.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_14.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_14.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_14.CausesValidation = true;
			this._optStoreType_14.Enabled = true;
			this._optStoreType_14.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_14.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_14.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_14.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_14.TabStop = true;
			this._optStoreType_14.Checked = false;
			this._optStoreType_14.Visible = true;
			this._optStoreType_14.Name = "_optStoreType_14";
			this._optStoreType_0.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_0.Text = "Bank";
			this._optStoreType_0.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_0.Location = new System.Drawing.Point(16, 24);
			this._optStoreType_0.TabIndex = 10;
			this._optStoreType_0.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_0.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_0.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_0.CausesValidation = true;
			this._optStoreType_0.Enabled = true;
			this._optStoreType_0.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_0.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_0.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_0.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_0.TabStop = true;
			this._optStoreType_0.Checked = false;
			this._optStoreType_0.Visible = true;
			this._optStoreType_0.Name = "_optStoreType_0";
			this._optStoreType_9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_9.Text = "Jail";
			this._optStoreType_9.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_9.Location = new System.Drawing.Point(152, 48);
			this._optStoreType_9.TabIndex = 19;
			this._optStoreType_9.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_9.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_9.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_9.CausesValidation = true;
			this._optStoreType_9.Enabled = true;
			this._optStoreType_9.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_9.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_9.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_9.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_9.TabStop = true;
			this._optStoreType_9.Checked = false;
			this._optStoreType_9.Visible = true;
			this._optStoreType_9.Name = "_optStoreType_9";
			this._optStoreType_8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_8.Text = "Healer";
			this._optStoreType_8.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_8.Location = new System.Drawing.Point(152, 24);
			this._optStoreType_8.TabIndex = 18;
			this._optStoreType_8.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_8.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_8.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_8.CausesValidation = true;
			this._optStoreType_8.Enabled = true;
			this._optStoreType_8.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_8.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_8.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_8.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_8.TabStop = true;
			this._optStoreType_8.Checked = false;
			this._optStoreType_8.Visible = true;
			this._optStoreType_8.Name = "_optStoreType_8";
			this._optStoreType_7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_7.Text = "Raft / Climing gear";
			this._optStoreType_7.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_7.Location = new System.Drawing.Point(16, 192);
			this._optStoreType_7.TabIndex = 17;
			this._optStoreType_7.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_7.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_7.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_7.CausesValidation = true;
			this._optStoreType_7.Enabled = true;
			this._optStoreType_7.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_7.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_7.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_7.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_7.TabStop = true;
			this._optStoreType_7.Checked = false;
			this._optStoreType_7.Visible = true;
			this._optStoreType_7.Name = "_optStoreType_7";
			this._optStoreType_6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_6.Text = "Lending";
			this._optStoreType_6.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_6.Location = new System.Drawing.Point(16, 168);
			this._optStoreType_6.TabIndex = 16;
			this._optStoreType_6.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_6.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_6.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_6.CausesValidation = true;
			this._optStoreType_6.Enabled = true;
			this._optStoreType_6.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_6.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_6.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_6.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_6.TabStop = true;
			this._optStoreType_6.Checked = false;
			this._optStoreType_6.Visible = true;
			this._optStoreType_6.Name = "_optStoreType_6";
			this._optStoreType_5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_5.Text = "Blackjack";
			this._optStoreType_5.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_5.Location = new System.Drawing.Point(16, 144);
			this._optStoreType_5.TabIndex = 15;
			this._optStoreType_5.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_5.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_5.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_5.CausesValidation = true;
			this._optStoreType_5.Enabled = true;
			this._optStoreType_5.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_5.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_5.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_5.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_5.TabStop = true;
			this._optStoreType_5.Checked = false;
			this._optStoreType_5.Visible = true;
			this._optStoreType_5.Name = "_optStoreType_5";
			this._optStoreType_4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_4.Text = "Armor Training";
			this._optStoreType_4.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_4.Location = new System.Drawing.Point(16, 120);
			this._optStoreType_4.TabIndex = 14;
			this._optStoreType_4.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_4.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_4.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_4.CausesValidation = true;
			this._optStoreType_4.Enabled = true;
			this._optStoreType_4.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_4.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_4.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_4.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_4.TabStop = true;
			this._optStoreType_4.Checked = false;
			this._optStoreType_4.Visible = true;
			this._optStoreType_4.Name = "_optStoreType_4";
			this._optStoreType_2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_2.Text = "Armor";
			this._optStoreType_2.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_2.Location = new System.Drawing.Point(16, 72);
			this._optStoreType_2.TabIndex = 12;
			this._optStoreType_2.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_2.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_2.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_2.CausesValidation = true;
			this._optStoreType_2.Enabled = true;
			this._optStoreType_2.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_2.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_2.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_2.TabStop = true;
			this._optStoreType_2.Checked = false;
			this._optStoreType_2.Visible = true;
			this._optStoreType_2.Name = "_optStoreType_2";
			this._optStoreType_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_1.Text = "Weapon";
			this._optStoreType_1.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_1.Location = new System.Drawing.Point(16, 48);
			this._optStoreType_1.TabIndex = 11;
			this._optStoreType_1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_1.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_1.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_1.CausesValidation = true;
			this._optStoreType_1.Enabled = true;
			this._optStoreType_1.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_1.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_1.TabStop = true;
			this._optStoreType_1.Checked = false;
			this._optStoreType_1.Visible = true;
			this._optStoreType_1.Name = "_optStoreType_1";
			this._optStoreType_3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_3.Text = "Weapon Training";
			this._optStoreType_3.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_3.Location = new System.Drawing.Point(16, 96);
			this._optStoreType_3.TabIndex = 13;
			this._optStoreType_3.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_3.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_3.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_3.CausesValidation = true;
			this._optStoreType_3.Enabled = true;
			this._optStoreType_3.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_3.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_3.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_3.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_3.TabStop = true;
			this._optStoreType_3.Checked = false;
			this._optStoreType_3.Visible = true;
			this._optStoreType_3.Name = "_optStoreType_3";
			this._optStoreType_10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_10.Text = "Fortune Teller";
			this._optStoreType_10.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_10.Location = new System.Drawing.Point(152, 72);
			this._optStoreType_10.TabIndex = 20;
			this._optStoreType_10.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_10.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_10.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_10.CausesValidation = true;
			this._optStoreType_10.Enabled = true;
			this._optStoreType_10.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_10.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_10.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_10.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_10.TabStop = true;
			this._optStoreType_10.Checked = false;
			this._optStoreType_10.Visible = true;
			this._optStoreType_10.Name = "_optStoreType_10";
			this.txtName.AutoSize = false;
			this.txtName.Size = new System.Drawing.Size(177, 19);
			this.txtName.Location = new System.Drawing.Point(96, 224);
			this.txtName.TabIndex = 27;
			this.txtName.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtName.AcceptsReturn = true;
			this.txtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtName.BackColor = System.Drawing.SystemColors.Window;
			this.txtName.CausesValidation = true;
			this.txtName.Enabled = true;
			this.txtName.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtName.HideSelection = true;
			this.txtName.ReadOnly = false;
			this.txtName.MaxLength = 0;
			this.txtName.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtName.Multiline = false;
			this.txtName.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtName.TabStop = true;
			this.txtName.Visible = true;
			this.txtName.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtName.Name = "txtName";
			this.txtPrice.AutoSize = false;
			this.txtPrice.Size = new System.Drawing.Size(73, 19);
			this.txtPrice.Location = new System.Drawing.Point(96, 248);
			this.txtPrice.TabIndex = 29;
			this.txtPrice.Text = "100";
			this.txtPrice.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.txtPrice.AcceptsReturn = true;
			this.txtPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtPrice.BackColor = System.Drawing.SystemColors.Window;
			this.txtPrice.CausesValidation = true;
			this.txtPrice.Enabled = true;
			this.txtPrice.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtPrice.HideSelection = true;
			this.txtPrice.ReadOnly = false;
			this.txtPrice.MaxLength = 0;
			this.txtPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtPrice.Multiline = false;
			this.txtPrice.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtPrice.TabStop = true;
			this.txtPrice.Visible = true;
			this.txtPrice.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtPrice.Name = "txtPrice";
			this._optStoreType_11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_11.Text = "Flip Flop";
			this._optStoreType_11.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_11.Location = new System.Drawing.Point(152, 96);
			this._optStoreType_11.TabIndex = 21;
			this._optStoreType_11.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_11.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_11.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_11.CausesValidation = true;
			this._optStoreType_11.Enabled = true;
			this._optStoreType_11.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_11.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_11.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_11.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_11.TabStop = true;
			this._optStoreType_11.Checked = false;
			this._optStoreType_11.Visible = true;
			this._optStoreType_11.Name = "_optStoreType_11";
			this._optStoreType_12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_12.Text = "Pawn";
			this._optStoreType_12.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_12.Location = new System.Drawing.Point(152, 120);
			this._optStoreType_12.TabIndex = 22;
			this._optStoreType_12.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_12.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_12.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_12.CausesValidation = true;
			this._optStoreType_12.Enabled = true;
			this._optStoreType_12.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_12.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_12.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_12.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_12.TabStop = true;
			this._optStoreType_12.Checked = false;
			this._optStoreType_12.Visible = true;
			this._optStoreType_12.Name = "_optStoreType_12";
			this._optStoreType_13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_13.Text = "Food";
			this._optStoreType_13.Size = new System.Drawing.Size(119, 17);
			this._optStoreType_13.Location = new System.Drawing.Point(152, 144);
			this._optStoreType_13.TabIndex = 23;
			this._optStoreType_13.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this._optStoreType_13.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this._optStoreType_13.BackColor = System.Drawing.SystemColors.Control;
			this._optStoreType_13.CausesValidation = true;
			this._optStoreType_13.Enabled = true;
			this._optStoreType_13.ForeColor = System.Drawing.SystemColors.ControlText;
			this._optStoreType_13.Cursor = System.Windows.Forms.Cursors.Default;
			this._optStoreType_13.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._optStoreType_13.Appearance = System.Windows.Forms.Appearance.Normal;
			this._optStoreType_13.TabStop = true;
			this._optStoreType_13.Checked = false;
			this._optStoreType_13.Visible = true;
			this._optStoreType_13.Name = "_optStoreType_13";
			this.Label8.Text = "Store Name";
			this.Label8.Size = new System.Drawing.Size(81, 17);
			this.Label8.Location = new System.Drawing.Point(16, 224);
			this.Label8.TabIndex = 25;
			this.Label8.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label8.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label8.BackColor = System.Drawing.SystemColors.Control;
			this.Label8.Enabled = true;
			this.Label8.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label8.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label8.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label8.UseMnemonic = true;
			this.Label8.Visible = true;
			this.Label8.AutoSize = false;
			this.Label8.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label8.Name = "Label8";
			this.Label6.Text = "Price Factor";
			this.Label6.Size = new System.Drawing.Size(81, 17);
			this.Label6.Location = new System.Drawing.Point(16, 248);
			this.Label6.TabIndex = 24;
			this.Label6.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label6.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label6.BackColor = System.Drawing.SystemColors.Control;
			this.Label6.Enabled = true;
			this.Label6.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label6.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label6.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label6.UseMnemonic = true;
			this.Label6.Visible = true;
			this.Label6.AutoSize = false;
			this.Label6.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label6.Name = "Label6";
			this.Label9.Text = "Height";
			this.Label9.Size = new System.Drawing.Size(89, 25);
			this.Label9.Location = new System.Drawing.Point(16, 104);
			this.Label9.TabIndex = 39;
			this.Label9.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label9.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label9.BackColor = System.Drawing.SystemColors.Control;
			this.Label9.Enabled = true;
			this.Label9.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label9.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label9.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label9.UseMnemonic = true;
			this.Label9.Visible = true;
			this.Label9.AutoSize = false;
			this.Label9.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label9.Name = "Label9";
			this.Label1.Text = "Width";
			this.Label1.Size = new System.Drawing.Size(81, 17);
			this.Label1.Location = new System.Drawing.Point(16, 80);
			this.Label1.TabIndex = 38;
			this.Label1.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label1.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label1.BackColor = System.Drawing.SystemColors.Control;
			this.Label1.Enabled = true;
			this.Label1.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label1.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label1.UseMnemonic = true;
			this.Label1.Visible = true;
			this.Label1.AutoSize = false;
			this.Label1.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label1.Name = "Label1";
			this.lblSpecialData.Text = "Label5";
			this.lblSpecialData.Size = new System.Drawing.Size(305, 33);
			this.lblSpecialData.Location = new System.Drawing.Point(192, 328);
			this.lblSpecialData.TabIndex = 35;
			this.lblSpecialData.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.lblSpecialData.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.lblSpecialData.BackColor = System.Drawing.SystemColors.Control;
			this.lblSpecialData.Enabled = true;
			this.lblSpecialData.ForeColor = System.Drawing.SystemColors.ControlText;
			this.lblSpecialData.Cursor = System.Windows.Forms.Cursors.Default;
			this.lblSpecialData.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.lblSpecialData.UseMnemonic = true;
			this.lblSpecialData.Visible = true;
			this.lblSpecialData.AutoSize = false;
			this.lblSpecialData.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.lblSpecialData.Name = "lblSpecialData";
			this.Label5.Text = "Special Data";
			this.Label5.Size = new System.Drawing.Size(81, 17);
			this.Label5.Location = new System.Drawing.Point(192, 312);
			this.Label5.TabIndex = 34;
			this.Label5.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label5.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label5.BackColor = System.Drawing.SystemColors.Control;
			this.Label5.Enabled = true;
			this.Label5.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label5.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label5.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label5.UseMnemonic = true;
			this.Label5.Visible = true;
			this.Label5.AutoSize = false;
			this.Label5.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label5.Name = "Label5";
			this.Label7.Text = "Special Event Location";
			this.Label7.Size = new System.Drawing.Size(81, 33);
			this.Label7.Location = new System.Drawing.Point(16, 24);
			this.Label7.TabIndex = 32;
			this.Label7.Font = new System.Drawing.Font("Arial", 8, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
			this.Label7.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label7.BackColor = System.Drawing.SystemColors.Control;
			this.Label7.Enabled = true;
			this.Label7.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label7.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label7.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label7.UseMnemonic = true;
			this.Label7.Visible = true;
			this.Label7.AutoSize = false;
			this.Label7.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label7.Name = "Label7";
			this.Controls.Add(frmDoor);
			this.Controls.Add(frmChest);
			this.Controls.Add(frmSpeakWith);
			this.Controls.Add(txtSpcHeight);
			this.Controls.Add(txtSpcWidth);
			this.Controls.Add(Frame1);
			this.Controls.Add(txtLocY);
			this.Controls.Add(txtLocX);
			this.Controls.Add(frmMapChange);
			this.Controls.Add(cmdCancel);
			this.Controls.Add(cmdOK);
			this.Controls.Add(frmStore);
			this.Controls.Add(Label9);
			this.Controls.Add(Label1);
			this.Controls.Add(lblSpecialData);
			this.Controls.Add(Label5);
			this.Controls.Add(Label7);
			this.frmDoor.Controls.Add(cboDoorKey);
			this.frmDoor.Controls.Add(Label10);
			this.frmChest.Controls.Add(txtGold);
			this.frmChest.Controls.Add(_optTreasure_1);
			this.frmChest.Controls.Add(_optTreasure_0);
			this.frmChest.Controls.Add(cboChestItem);
			this.frmSpeakWith.Controls.Add(_optSpeakWith_2);
			this.frmSpeakWith.Controls.Add(_optSpeakWith_1);
			this.Frame1.Controls.Add(_optType_25);
			this.Frame1.Controls.Add(_optType_24);
			this.Frame1.Controls.Add(_optType_23);
			this.Frame1.Controls.Add(_optType_22);
			this.Frame1.Controls.Add(_optType_1);
			this.Frame1.Controls.Add(_optType_2);
			this.Frame1.Controls.Add(_optType_20);
			this.Frame1.Controls.Add(_optType_21);
			this.frmMapChange.Controls.Add(chkAutoChange);
			this.frmMapChange.Controls.Add(txtNewX);
			this.frmMapChange.Controls.Add(txtNewY);
			this.frmMapChange.Controls.Add(txtNewMap);
			this.frmMapChange.Controls.Add(Label2);
			this.frmMapChange.Controls.Add(Label3);
			this.frmMapChange.Controls.Add(Label4);
			this.frmStore.Controls.Add(_optStoreType_15);
			this.frmStore.Controls.Add(_optStoreType_14);
			this.frmStore.Controls.Add(_optStoreType_0);
			this.frmStore.Controls.Add(_optStoreType_9);
			this.frmStore.Controls.Add(_optStoreType_8);
			this.frmStore.Controls.Add(_optStoreType_7);
			this.frmStore.Controls.Add(_optStoreType_6);
			this.frmStore.Controls.Add(_optStoreType_5);
			this.frmStore.Controls.Add(_optStoreType_4);
			this.frmStore.Controls.Add(_optStoreType_2);
			this.frmStore.Controls.Add(_optStoreType_1);
			this.frmStore.Controls.Add(_optStoreType_3);
			this.frmStore.Controls.Add(_optStoreType_10);
			this.frmStore.Controls.Add(txtName);
			this.frmStore.Controls.Add(txtPrice);
			this.frmStore.Controls.Add(_optStoreType_11);
			this.frmStore.Controls.Add(_optStoreType_12);
			this.frmStore.Controls.Add(_optStoreType_13);
			this.frmStore.Controls.Add(Label8);
			this.frmStore.Controls.Add(Label6);
			this.optSpeakWith.SetIndex(_optSpeakWith_2, 2);
			this.optSpeakWith.SetIndex(_optSpeakWith_1, 1);
			this.optStoreType.SetIndex(_optStoreType_15, 15);
			this.optStoreType.SetIndex(_optStoreType_14, 14);
			this.optStoreType.SetIndex(_optStoreType_0, 0);
			this.optStoreType.SetIndex(_optStoreType_9, 9);
			this.optStoreType.SetIndex(_optStoreType_8, 8);
			this.optStoreType.SetIndex(_optStoreType_7, 7);
			this.optStoreType.SetIndex(_optStoreType_6, 6);
			this.optStoreType.SetIndex(_optStoreType_5, 5);
			this.optStoreType.SetIndex(_optStoreType_4, 4);
			this.optStoreType.SetIndex(_optStoreType_2, 2);
			this.optStoreType.SetIndex(_optStoreType_1, 1);
			this.optStoreType.SetIndex(_optStoreType_3, 3);
			this.optStoreType.SetIndex(_optStoreType_10, 10);
			this.optStoreType.SetIndex(_optStoreType_11, 11);
			this.optStoreType.SetIndex(_optStoreType_12, 12);
			this.optStoreType.SetIndex(_optStoreType_13, 13);
			this.optTreasure.SetIndex(_optTreasure_1, 1);
			this.optTreasure.SetIndex(_optTreasure_0, 0);
			this.optType.SetIndex(_optType_25, 25);
			this.optType.SetIndex(_optType_24, 24);
			this.optType.SetIndex(_optType_23, 23);
			this.optType.SetIndex(_optType_22, 22);
			this.optType.SetIndex(_optType_1, 1);
			this.optType.SetIndex(_optType_2, 2);
			this.optType.SetIndex(_optType_20, 20);
			this.optType.SetIndex(_optType_21, 21);
			((System.ComponentModel.ISupportInitialize) this.optType).EndInit();
			((System.ComponentModel.ISupportInitialize) this.optTreasure).EndInit();
			((System.ComponentModel.ISupportInitialize) this.optStoreType).EndInit();
			((System.ComponentModel.ISupportInitialize) this.optSpeakWith).EndInit();
			this.frmDoor.ResumeLayout(false);
			this.frmChest.ResumeLayout(false);
			this.frmSpeakWith.ResumeLayout(false);
			this.Frame1.ResumeLayout(false);
			this.frmMapChange.ResumeLayout(false);
			this.frmStore.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		#endregion
	}
}
