//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define IDS_STRING1                     1
#define IDS_STRING2                     2
#define IDS_STRING3                     3
#define IDS_STRING4                     4
#define map_ThompsonCrossing            4
#define IDS_STRING5                     5
#define IDS_STRING6                     6
#define IDS_STRING7                     7
#define IDS_STRING8                     8
#define IDS_STRING9                     9
#define IDS_STRING10                    10
#define IDS_STRING11                    11
#define IDS_STRING12                    12
#define IDS_STRING13                    13
#define IDS_STRING14                    14
#define IDS_STRING15                    15
#define IDS_STRING16                    16
#define IDS_STRING17                    17
#define IDS_STRING18                    18
#define IDS_STRING19                    19
#define IDS_STRING20                    20
#define IDS_STRING21                    21
#define IDS_STRING22                    22
#define IDS_STRING23                    23
#define IDS_STRING24                    24
#define IDS_STRING25                    25
#define IDS_STRING26                    26
#define IDS_STRING27                    27
#define IDS_STRING28                    28
#define IDS_STRING29                    29
#define IDS_STRING30                    30
#define IDS_STRING31                    31
#define IDS_STRING32                    32
#define IDS_STRING33                    33
#define IDS_STRING34                    34
#define IDS_STRING35                    35
#define IDS_STRING36                    36
#define IDS_STRING37                    37
#define IDS_STRING38                    38
#define IDS_STRING39                    39
#define IDS_STRING40                    40
#define IDS_STRING41                    41
#define IDS_STRING42                    42
#define IDS_STRING43                    43
#define IDS_STRING44                    44
#define IDS_STRING45                    45
#define IDS_STRING46                    46
#define IDS_STRING47                    47
#define IDS_STRING48                    48
#define IDB_BITMAP2                     102
#define LOTA_CHARACTER                  119
#define LOTA_FONT                       120
#define LOTA_TILES                      121
#define OUTSIDE1                        122
#define map_OUTSIDE1                    122
#define LOTA_MENU                       123
#define LOTA_ACCEL                      124
#define snd_WalkOutside                 126
#define snd_Bump                        127
#define snd_Swamp                       128
#define snd_Desert                      129
#define snd_Question                    130
#define snd_Invalid                     131
#define snd_Raft                        132
#define Dng_Pirates                     133
#define DUNGEON_WALL                    134
#define DUNGEON_FLOOR                   135
#define DUNGEON_CEILING                 136
#define DUNGEON_FLOORHOLE               137
#define dlgOptions                      138
#define snd_VeryBad                     139
#define snd_Raft1                       140
#define snd_Ocean1                      141
#define snd_Ocean2                      142
#define snd_VeryGood                    143
#define snd_Mountains                   144
#define snd_BoardRaft                   145
#define map_Thornberry                  146
#define LOTA_TOWNTILES                  147
#define snd_EnemyDie                    148
#define snd_EnemyHit                    149
#define snd_EnemyMiss                   150
#define snd_PlayerHit                   151
#define snd_PlayerMiss                  152
#define snd_Medium                      153
#define snd_TownWalk                    154
#define snd_Sale                        155
#define ICON_LOTA                       156
#define snd_BuildingClose               157
#define snd_BuildingOpen                158
#define dlgAboutBox                     159
#define LOTA_CASTLETILES                160
#define map_Castle                      161
#define snd_Good                        162
#define map_Alanville                   165
#define map_BigRapids                   166
#define map_Cobbleton                   167
#define map_IsleCity                    168
#define map_GrandLedge                  169
#define snd_OpenChest                   170
#define snd_UnlockDoor                  171
#define map_Castle2                     172
#define map_Mazelton                    174
#define map_OUTSIDE2                    175
#define map_EagleHollow                 176
#define map_HolyPoint                   177
#define map_Laingsburg                  178
#define map_MerchantSquare              179
#define LOTA_OVERLANDMONSTERS           181
#define dat_Monst1                      182
#define snd_Encounter                   183
#define ID_FILE_SAVEGAME                184
#define IDB_BITMAP1                     185
#define LOTA_TITLE                      185
#define chk3DAccel                      1001
#define chkZBuffer                      1002
#define chkNewGraphics                  1003
#define cmdOK                           1004
#define cmdCancel                       1005
#define IDABOUTOK                       1006
#define chkDisableEncounter             1008
#define ID_FILE_NEWGAME                 40001
#define ID_FILE_RESTARTGAME             40002
#define ID_FILE_QUIT                    40004
#define ID_OPTIONS_TOGGLEFULLSCREEN     40005
#define D_OPTIONS_TOGGLEFULLSCREEN      40006
#define ID_OPTIONS_PREFERENCES          40007
#define ID_HELP_ABOUT                   40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
