//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERY.Xle.Data
{
    using System;
    using System.Collections.Generic;
    using AgateLib.Data;
    
    public sealed class AgateDataImport
    {
        private List<Monster> mMonsterList = new List<Monster>();
        public AgateDataImport(AgateDatabase dbase)
        {
            Int32 i;
            for (i = 0; (i < dbase.Tables["Monster"].Rows.Count); i = (i + 1))
            {
                this.mMonsterList.Add(new Monster(dbase.Tables["Monster"].Rows[i]));
            }
        }
        public List<Monster> MonsterList
        {
            get
            {
                return this.mMonsterList;
            }
        }
    }
    public sealed class Monster
    {
        private int mWeapon;
        private int mFood;
        private int mImage;
        private int mFriendly;
        private bool mTalks;
        private int mGold;
        private int mTerrain;
        private string mName;
        private int mHP;
        private int mDefense;
        private int mAttack;
        internal Monster(AgateLib.Data.AgateRow row)
        {
            this.mWeapon = Int32.Parse(row["Weapon"]);
            this.mFood = Int32.Parse(row["Food"]);
            this.mImage = Int32.Parse(row["Image"]);
            this.mFriendly = Int32.Parse(row["Friendly"]);
            this.mTalks = Boolean.Parse(row["Talks"]);
            this.mGold = Int32.Parse(row["Gold"]);
            this.mTerrain = Int32.Parse(row["Terrain"]);
            this.mName = row["Name"];
            this.mHP = Int32.Parse(row["HP"]);
            this.mDefense = Int32.Parse(row["Defense"]);
            this.mAttack = Int32.Parse(row["Attack"]);
        }
        /// <summary>
        /// Weapon column.
        /// </summary>
        public int Weapon
        {
            get
            {
                return this.mWeapon;
            }
        }
        /// <summary>
        /// Food column.
        /// </summary>
        public int Food
        {
            get
            {
                return this.mFood;
            }
        }
        /// <summary>
        /// Image column.
        /// </summary>
        public int Image
        {
            get
            {
                return this.mImage;
            }
        }
        /// <summary>
        /// Friendly column.
        /// </summary>
        public int Friendly
        {
            get
            {
                return this.mFriendly;
            }
        }
        /// <summary>
        /// Talks column.
        /// </summary>
        public bool Talks
        {
            get
            {
                return this.mTalks;
            }
        }
        /// <summary>
        /// Gold column.
        /// </summary>
        public int Gold
        {
            get
            {
                return this.mGold;
            }
        }
        /// <summary>
        /// Terrain column.
        /// </summary>
        public int Terrain
        {
            get
            {
                return this.mTerrain;
            }
        }
        /// <summary>
        /// Name column.
        /// </summary>
        public string Name
        {
            get
            {
                return this.mName;
            }
        }
        /// <summary>
        /// HP column.
        /// </summary>
        public int HP
        {
            get
            {
                return this.mHP;
            }
        }
        /// <summary>
        /// Defense column.
        /// </summary>
        public int Defense
        {
            get
            {
                return this.mDefense;
            }
        }
        /// <summary>
        /// Attack column.
        /// </summary>
        public int Attack
        {
            get
            {
                return this.mAttack;
            }
        }
    }
}
